apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-music-demo
  namespace: kafka-music-demo
spec:
  releaseName: kafka-music-demo
  chart:
    spec:
      chart: kafka-music-demo
      sourceRef:
        kind: HelmRepository
        name: kafka-music-demo
  interval: 10m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      className: nginx