apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: simple-streaming-app-helm-repo
  namespace: demo-apps
spec:
  interval: 1m
  type: oci
  url: oci://ghcr.io/gphilipp/charts
  secretRef:
    name: docker-regcred