apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-music-demo
  namespace: kafka-music-demo
spec:
  chart:
    spec:
      version: ">=0.1-alpha"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: kafka-music-demo.staging
          paths:
            - path: /
              pathType: ImplementationSpecific
