apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: simple-streaming-app
  namespace: simple-streaming-app
spec:
  chart:
    spec:
      version: ">=0.3-alpha"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: simple-streaming-app.staging
          paths:
            - path: /
              pathType: ImplementationSpecific
